{
 "title": "Swarm",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Kademlia Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "bee_kademlia_currently_connected_peers{}"
    }
   ]
  },
  {
   "title": "Kademlia Known Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "bee_kademlia_currently_known_peers{}"
    }
   ]
  },
  {
   "title": "Kademlia Current Depth",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "bee_kademlia_current_depth{job!=\"pod-snarlbee-headless\"}"
    }
   ]
  }
 ]
}